theme: jekyll-theme-minimal
title: Room no. 308
description: The room of our random experiments
markdown: kramdown
kramdown:
    math_engine: mathjax
google_analytics: UA-192680612-1

url: "https://roomno308.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap